#pragma once

#ifdef INKHUD_RU
#define INK_APPLET_MESHTASTIC "Meshtastic RU"
#define INK_APPLET_EXIT "Выход"
#define INK_APPLET_ALL_MESSAGES "Все сообщения"
#define INK_APPLET_POSITIONS "Позиции"
#define INK_APPLET_HEARD "Обнаруженный"
#define INK_APPLET_RECENT_LIST "Недавние"
#define INK_APPLET_MAP_NODE_POS "Позиции нод"
#define INK_APPLET_MAP_NODE_POS_1 "отображаются тут"
#define INK_APPLET_CHANNEL "Канал"
#define INK_APPLET_CHANNEL_PUBLIC "Открытый"
#define INK_APPLET_CHANNEL_0 "Канал 0"
#define INK_APPLET_CHANNEL_1 "Канал 1"
#define INK_APPLET_NEXT_TILE "След>"
#define INK_APPLET_REBOOT "Перезагрузить"
#define INK_APPLET_REBOOT_DEVICE "Перезагрузить устройство?"
#define INK_APPLET_REBOOT_BANNER "Перезагрузка..."
#define INK_APPLET_SHUTDOWN_BANNER "Выключение..."
#define INK_APPLET_SHUTDOWN "Выключить"
#define INK_APPLET_SHUTDOWN_DEVICE "Выключить устройство?"
#define INK_APPLET_ONBOARD_BANNER "Приветствуем в Meshtastic!\nНажмите кнопку Выбора\nдля открытия меню\nи выбрать действиеы."
#define INK_APPLET_ONBOARD_BANNER_TFT "Приветствуем в Meshtastic!\nCвайп для навигации и\nудерживать для выбора\nили открытия меню."
#define INK_APPLET_ONBOARD_BANNER_BTN "Приветствуем в  Meshtastic!\nКликните для навигации и\nудерживать для выбора\nили открытия меню."
#define INK_APPLET_ONBOARD_PRESS_BTN_CONTINUE "Нажмите чтобы продолжить"
#define INK_APPLET_OK "OK"
#define INK_APPLET_YES "Да"
#define INK_APPLET_CONFIRM "Потвердить"
#define INK_APPLET_NO "Нет"
#define INK_APPLET_ENABLED "Включить"
#define INK_APPLET_DISABLE "Отключить"
#define INK_APPLET_DISABLED "Выключить"
#define INK_APPLET_GOT_IT "Понятно!"
#define INK_APPLET_DISMISS "Отклонить"
#define INK_APPLET_ONLINE "онлайн"
#define INK_APPLET_min "мин"
#define INK_APPLET_BACK "Назад"
#define INK_APPLET_HOME "Главная"
#define INK_APPLET_HOME_ACTION "Действия"
#define INK_APPLET_NOTIFICATIONS "Уведомления"
#define INK_APPLET_OPTIONS "Настройки"
#define INK_APPLET_DISPLAY_OPTIONS "Настройки экрана"
#define INK_APPLET_DISPLAY_OPTIONS_BRIGHTNESS "Яркость"
#define INK_APPLET_DISPLAY_OPTIONS_SCREEN_COLOR "Цвет экрана"
#define INK_APPLET_DISPLAY_OPTIONS_DISPLAY_UNITS "Ед измерения"
#define INK_APPLET_BLUETOOTH_TOGGLE "Bluetooth Вкл/Выкл"
#define INK_APPLET_POWER "Питание"
#define INK_APPLET_REBOOT_OR_SHUTDOWN "Перезапуск/Выключение"
#define INK_APPLET_SYSTEM "Система"
#define INK_APPLET_SYSTEM_ACTION "Действия"
#define INK_APPLET_DEVICE_ROLE "Тип устройства"
#define INK_APPLET_RADIO_PRESET "Пресет радио"
#define INK_APPLET_SEND_POSITION "Отправить локацию"
#define INK_APPLET_SEND_NODE_INFO "Отправить инф об узле"
#define INK_APPLET_LORA_REGION "LoRa Регион"
#define INK_APPLET_LORA_REGION_SET "Задать LoRa регион"
#define INK_APPLET_LORA_ACTIONS "LoRa Действия"
#define INK_APPLET_CLOCK_TIMEZONE_PICK "Выбрать часовой пояс"
#define INK_APPLET_CLOCK_TIMEZONE "Часовой пояс"
#define INK_APPLET_CLOCK_FACE "Вид часов"
#define INK_APPLET_CLOCK_TIMEFORMAT "Формат времени"
#define INK_APPLET_CLOCK_FORMAT_12H "12-часовой"
#define INK_APPLET_CLOCK_FORMAT_24H "24-часовой"
#define INK_APPLET_GPS_FORMAT "GPS Формат"
#define INK_APPLET_GPS_COMPASS "Компас"
#define INK_APPLET_GPS_COMPASS_CALIBRATE "Калибровка компаса"
#define INK_APPLET_TOGGLE_BACKLIGHT "Вкл/Выкл подсветку"
#define INK_APPLET_FAVORITES "Избранное"
#define INK_APPLET_FAVORITES_ACTION "Действия"
#define INK_APPLET_FAVORITE_REMOVE "Удалить из Избранного"
#else
#define INK_APPLET_MESHTASTIC "Meshtastic"
#define INK_APPLET_EXIT "Exit"
#define INK_APPLET_ALL_MESSAGES "All Messages"
#define INK_APPLET_POSITIONS "Positions"
#define INK_APPLET_HEARD "Heard"
#define INK_APPLET_RECENT_LIST "Recents List"
#define INK_APPLET_MAP_NODE_POS "Node positions"
#define INK_APPLET_MAP_NODE_POS_1 "will appear here"
#define INK_APPLET_CHANNEL "Channel"
#define INK_APPLET_CHANNEL_PUBLIC "Public"
#define INK_APPLET_CHANNEL_0 "Channel 0"
#define INK_APPLET_CHANNEL_1 "Channel 1"
#define INK_APPLET_NEXT_TILE "Next Tile"
#define INK_APPLET_REBOOT "Reboot"
#define INK_APPLET_REBOOT_DEVICE "Reboot Device?"
#define INK_APPLET_REBOOT_BANNER "Rebooting..."
#define INK_APPLET_SHUTDOWN "Shutdown"
#define INK_APPLET_SHUTDOWN_DEVICE "Shutdown Device?"
#define INK_APPLET_SHUTDOWN_BANNER "Shutting Down..."
#define INK_APPLET_ONBOARD_BANNER "Welcome to Meshtastic!\nUse the Select button\nto open menus\nand make selections."
#define INK_APPLET_ONBOARD_BANNER_TFT "Welcome to Meshtastic!\nSwipe to navigate and\nlong press to select\nor open a menu."
#define INK_APPLET_ONBOARD_BANNER_BTN "Welcome to Meshtastic!\nClick to navigate and\nlong press to select\nor open a menu."
#define INK_APPLET_ONBOARD_PRESS_BTN_CONTINUE "Press button to continue"
#define INK_APPLET_OK "ОК"
#define INK_APPLET_YES "Yes"
#define INK_APPLET_CONFIRM "Confirm"
#define INK_APPLET_NO "No"
#define INK_APPLET_ENABLED "Enabled"
#define INK_APPLET_DISABLE "Disable"
#define INK_APPLET_DISABLED "Disabled"
#define INK_APPLET_GOT_IT "Got it!"
#define INK_APPLET_DISMISS "Dismiss"
#define INK_APPLET_ONLINE "online"
#define INK_APPLET_min "mins"
#define INK_APPLET_BACK "Back"
#define INK_APPLET_HOME "Home"
#define INK_APPLET_HOME_ACTION "Home Action"
#define INK_APPLET_NOTIFICATIONS "Notifications"
#define INK_APPLET_OPTIONS "Options"
#define INK_APPLET_DISPLAY_OPTIONS "Display Options"
#define INK_APPLET_DISPLAY_OPTIONS_BRIGHTNESS "Brightness"
#define INK_APPLET_DISPLAY_OPTIONS_SCREEN_COLOR "Screen Color"
#define INK_APPLET_DISPLAY_OPTIONS_DISPLAY_UNITS "Display Units"
#define INK_APPLET_BLUETOOTH_TOGGLE "Bluetooth Toggle"
#define INK_APPLET_POWER "Power"
#define INK_APPLET_REBOOT_OR_SHUTDOWN "Reboot/Shutdown"
#define INK_APPLET_SYSTEM "System"
#define INK_APPLET_SYSTEM_ACTION "System Action"
#define INK_APPLET_DEVICE_ROLE "Device Role"
#define INK_APPLET_RADIO_PRESET "Radio Preset"
#define INK_APPLET_SEND_POSITION "Send Position"
#define INK_APPLET_SEND_NODE_INFO "Send Node Info"
#define INK_APPLET_LORA_REGION "LoRa Region"
#define INK_APPLET_LORA_REGION_SET "Set the LoRa region"
#define INK_APPLET_LORA_ACTIONS "LoRa Actions"
#define INK_APPLET_CLOCK_TIMEZONE_PICK "Pick Timezone"
#define INK_APPLET_CLOCK_TIMEZONE "Timezone"
#define INK_APPLET_CLOCK_FACE "Clock Face"
#define INK_APPLET_CLOCK_TIMEFORMAT "Time Format"
#define INK_APPLET_CLOCK_FORMAT_12H "12-hour"
#define INK_APPLET_CLOCK_FORMAT_24H "24-hour"
#define INK_APPLET_GPS_FORMAT "GPS Format"
#define INK_APPLET_GPS_COMPASS "Compass"
#define INK_APPLET_GPS_COMPASS_CALIBRATE "Compass Calibrate"
#define INK_APPLET_TOGGLE_BACKLIGHT "Toggle Backlight"
#define INK_APPLET_FAVORITES "Favorites"
#define INK_APPLET_FAVORITES_ACTION "Favorites Action"
#define INK_APPLET_FAVORITE_REMOVE "Remove Favorite"
#endif