#include "ScreenFonts.h"

#ifdef OLED_RU
#define MSG_ONBOARD_BANNER "Приветствуем в Meshtastic!\nНажмите кнопку Выбора\nдля открытия меню\nи выбрать действиеы."
#define MSG_ONBOARD_BANNER_TFT "Приветствуем в Meshtastic!\nCвайп для навигации и\nудерживать для выбора\nили открытия меню."
#define MSG_ONBOARD_BANNER_BTN "Приветствуем в  Meshtastic!\nКликните для навигации и\nудерживать для выбора\nили открытия меню."
#define MSG_OK "OK"
#define MSG_YES "Да"
#define MSG_CONFIRM "Потвердить"
#define MSG_NO "Нет"
#define MSG_ENABLED "Включить"
#define MSG_DISABLE "Отключить"
#define MSG_DISABLED "Выключить"
#define MSG_GOT_IT "Понятно!"
#define MSG_DISMISS "Отклонить"
#define MSG_ONLINE "онлайн"
#define MSG_BACK "Назад"
#define MSG_HOME "Главная"
#define MSG_HOME_ACTION "Действия"
#define MSG_NOTIFICATIONS "Уведомления"
#define MSG_DISPLAY_OPTIONS "Настройки экрана"
#define MSG_DISPLAY_OPTIONS_BRIGHTNESS "Яркость"
#define MSG_DISPLAY_OPTIONS_SCREEN_COLOR "Цвет экрана"
#define MSG_DISPLAY_OPTIONS_DISPLAY_UNITS "Ед измерения"
#define MSG_BLUETOOTH_TOGGLE "Bluetooth Вкл/Выкл"
#define MSG_POWER "Питание"
#define MSG_REBOOT_OR_SHUTDOWN "Перезапуск/Выключение"
#define MSG_SYSTEM "Система"
#define MSG_SYSTEM_ACTION "Действия"
#define MSG_DEVICE_ROLE "Тип устройства"
#define MSG_RADIO_PRESET "Пресет радио"
#define MSG_SEND_POSITION "Отправить локацию"
#define MSG_SEND_NODE_INFO "Отправить инф об узле"
#define MSG_LORA_REGION "LoRa Регион"
#define MSG_LORA_REGION_SET "Задать LoRa регион"
#define MSG_LORA_ACTIONS "LoRa Действия"
#define MSG_CLOCK_TIMEZONE_PICK "Выбрать часовой пояс"
#define MSG_CLOCK_TIMEZONE "Часовой пояс"
#define MSG_CLOCK_FACE "Вид часов"
#define MSG_CLOCK_TIMEFORMAT "Формат времени"
#define MSG_CLOCK_FORMAT_12H "12-часовой"
#define MSG_CLOCK_FORMAT_24H "24-часовой"
#define MSG_GPS_FORMAT "GPS Формат"
#define MSG_GPS_COMPASS "Компас"
#define MSG_GPS_COMPASS_CALIBRATE "Калибровка компаса"
#define MSG_REBOOT "Перезагрузить"
#define MSG_REBOOT_DEVICE "Перезагрузить устройство?"
#define MSG_REBOOT_BANNER "Перезагрузка..."
#define MSG_TOGGLE_BACKLIGHT "Вкл/Выкл подсветку"
#define MSG_FAVORITES "Избранное"
#define MSG_FAVORITES_ACTION "Действия"
#define MSG_FAVORITE_REMOVE "Удалить из Избранного"
#define MSG_SHUTDOWN "Выключить"
#define MSG_SHUTDOWN_DEVICE "Выключить устройство?"
#else
#define MSG_ONBOARD_BANNER "Welcome to Meshtastic!\nUse the Select button\nto open menus\nand make selections."
#define MSG_ONBOARD_BANNER_TFT "Welcome to Meshtastic!\nSwipe to navigate and\nlong press to select\nor open a menu."
#define MSG_ONBOARD_BANNER_BTN "Welcome to Meshtastic!\nClick to navigate and\nlong press to select\nor open a menu."
#define MSG_OK "ОК"
#define MSG_YES "Yes"
#define MSG_CONFIRM "Confirm"
#define MSG_NO "No"
#define MSG_ENABLED "Enabled"
#define MSG_DISABLE "Disable"
#define MSG_DISABLED "Disabled"
#define MSG_GOT_IT "Got it!"
#define MSG_DISMISS "Dismiss"
#define MSG_ONLINE "online"
#define MSG_BACK "Back"
#define MSG_HOME "Home"
#define MSG_HOME_ACTION "Home Action"
#define MSG_NOTIFICATIONS "Notifications"
#define MSG_DISPLAY_OPTIONS "Display Options"
#define MSG_DISPLAY_OPTIONS_BRIGHTNESS "Brightness"
#define MSG_DISPLAY_OPTIONS_SCREEN_COLOR "Screen Color"
#define MSG_DISPLAY_OPTIONS_DISPLAY_UNITS "Display Units"
#define MSG_BLUETOOTH_TOGGLE "Bluetooth Toggle"
#define MSG_POWER "Power"
#define MSG_REBOOT_OR_SHUTDOWN "Reboot/Shutdown"
#define MSG_SYSTEM "System"
#define MSG_SYSTEM_ACTION "System Action"
#define MSG_DEVICE_ROLE "Device Role"
#define MSG_RADIO_PRESET "Radio Preset"
#define MSG_SEND_POSITION "Send Position"
#define MSG_SEND_NODE_INFO "Send Node Info"
#define MSG_LORA_REGION "LoRa Region"
#define MSG_LORA_REGION_SET "Set the LoRa region"
#define MSG_LORA_ACTIONS "LoRa Actions"
#define MSG_CLOCK_TIMEZONE_PICK "Pick Timezone"
#define MSG_CLOCK_TIMEZONE "Timezone"
#define MSG_CLOCK_FACE "Clock Face"
#define MSG_CLOCK_TIMEFORMAT "Time Format"
#define MSG_CLOCK_FORMAT_12H "12-hour"
#define MSG_CLOCK_FORMAT_24H "24-hour"
#define MSG_GPS_FORMAT "GPS Format"
#define MSG_GPS_COMPASS "Compass"
#define MSG_GPS_COMPASS_CALIBRATE "Compass Calibrate"
#define MSG_REBOOT "Reboot"
#define MSG_REBOOT_DEVICE "Reboot Device?"
#define MSG_REBOOT_BANNER "Rebooting..."
#define MSG_TOGGLE_BACKLIGHT "Toggle Backlight"
#define MSG_FAVORITES "Favorites"
#define MSG_FAVORITES_ACTION "Favorites Action"
#define MSG_FAVORITE_REMOVE "Remove Favorite"
#define MSG_SHUTDOWN "Shutdown"
#define MSG_SHUTDOWN_DEVICE "Shutdown Device?"
#endif