#include "ScreenFonts.h"

#ifdef OLED_RU
#define MSG_ONBOARD_BANNER "Приветствуем в Meshtastic!\nНажмите кнопку Выбора\nдля открытия меню\nи выбрать действиеы."
#define MSG_ONBOARD_BANNER_TFT "Приветствуем в Meshtastic!\nCвайп для навигации и\nудерживать для выбора\nили открытия меню."
#define MSG_ONBOARD_BANNER_BTN "Приветствуем в  Meshtastic!\nКликните для навигации и\nудерживать для выбора\nили открытия меню."
#define MSG_OK "OK"
#define MSG_YES "Да"
#define MSG_CONFIRM "Потвердить"
#define MSG_NO "Нет"
#define MSG_ENABLED "Включить"
#define MSG_DISABLE "Отключить"
#define MSG_DISABLED "Выключить"
#define MSG_GOT_IT "Понятно!"
#define MSG_BACK "Назад"
#define MSG_HOME "Главная"
#define MSG_HOME_ACTION "Действия"
#define MSG_DEVICE_ROLE "Тип устройства"
#define MSG_RADIO_PRESET "Пресет радио"
#define MSG_LORA_REGION "LoRa Регион"
#define MSG_LORA_REGION_SET "Задать LoRa регион"
#define MSG_LORA_ACTIONS "LoRa Действия"
#define MSG_CLOCK_TIMEFORMAT "Формат времени"
#define MSG_CLOCK_FORMAT_12H "12-часовой"
#define MSG_CLOCK_FORMAT_24H "24-часовой"
#define MSG_REBOOT "Перезагрузить"
#define MSG_REBOOT_BANNER "Перезагрузка..."
#define MSG_TOGGLE_BACKLIGHT "Вкл/Выкл подсветку"
#define MSG_FAVORITES "Избранное"
#define MSG_SHUTDOWN "Выключить"
#define MSG_SHUTDOWN_DEVICE "Выключить устройство?"
#else
#define MSG_ONBOARD_BANNER "Welcome to Meshtastic!\nUse the Select button\nto open menus\nand make selections."
#define MSG_ONBOARD_BANNER_TFT "Welcome to Meshtastic!\nSwipe to navigate and\nlong press to select\nor open a menu."
#define MSG_ONBOARD_BANNER_BTN "Welcome to Meshtastic!\nClick to navigate and\nlong press to select\nor open a menu."
#define MSG_OK "ОК"
#define MSG_YES "Yes"
#define MSG_CONFIRM "Confirm"
#define MSG_NO "No"
#define MSG_ENABLED "Enabled"
#define MSG_DISABLE "Disable"
#define MSG_DISABLED "Disabled"
#define MSG_GOT_IT "Got it!"
#define MSG_BACK "Back"
#define MSG_HOME "Home"
#define MSG_HOME_ACTION "Home Action"
#define MSG_DEVICE_ROLE "Device Role"
#define MSG_RADIO_PRESET "Radio Preset"
#define MSG_LORA_REGION "LoRa Region"
#define MSG_LORA_REGION_SET "Set the LoRa region"
#define MSG_LORA_ACTIONS "LoRa Actions"
#define MSG_CLOCK_TIMEFORMAT "Time Format"
#define MSG_CLOCK_FORMAT_12H "12-hour"
#define MSG_CLOCK_FORMAT_24H "24-hour"
#define MSG_REBOOT "Reboot"
#define MSG_REBOOT_BANNER "Rebooting..."
#define MSG_TOGGLE_BACKLIGHT "Toggle Backlight"
#define MSG_FAVORITES "Favorites"
#define MSG_SHUTDOWN "Shutdown"
#define MSG_SHUTDOWN_DEVICE "Shutdown Device?"
#endif